/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_mercs_soundsend_JniUtil */

#ifndef _Included_xyz_mercs_soundsend_JniUtil
#define _Included_xyz_mercs_soundsend_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_mercs_soundsend_JniUtil
 * Method:    init
 * Signature: (Ljava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_xyz_mercs_soundsend_JniUtil_init
  (JNIEnv *, jclass, jstring, jint, jboolean);

/*
 * Class:     xyz_mercs_soundsend_JniUtil
 * Method:    deinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xyz_mercs_soundsend_JniUtil_deinit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
