/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_utils_JniUtil */

#ifndef _Included_com_example_utils_JniUtil
#define _Included_com_example_utils_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_utils_JniUtil
 * Method:    YUVInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_utils_JniUtil_YUVInit
  (JNIEnv *, jclass);

/*
 * Class:     com_example_utils_JniUtil
 * Method:    YUVDeinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_utils_JniUtil_YUVDeinit
  (JNIEnv *, jclass);

/*
 * Class:     com_example_utils_JniUtil
 * Method:    YUVSetCallbackObject
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_com_example_utils_JniUtil_YUVSetCallbackObject
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_example_utils_JniUtil
 * Method:    YUVSetCallbackMethodName
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_example_utils_JniUtil_YUVSetCallbackMethodName
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_example_utils_JniUtil
 * Method:    YUVLock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_utils_JniUtil_YUVLock
  (JNIEnv *, jclass);

/*
 * Class:     com_example_utils_JniUtil
 * Method:    YUVUnlock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_utils_JniUtil_YUVUnlock
  (JNIEnv *, jclass);

/*
 * Class:     com_example_utils_JniUtil
 * Method:    YUVSetEnable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_utils_JniUtil_YUVSetEnable
  (JNIEnv *, jclass);

/*
 * Class:     com_example_utils_JniUtil
 * Method:    YUVRenderY
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_utils_JniUtil_YUVRenderY
  (JNIEnv *, jclass);

/*
 * Class:     com_example_utils_JniUtil
 * Method:    YUVRenderU
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_utils_JniUtil_YUVRenderU
  (JNIEnv *, jclass);

/*
 * Class:     com_example_utils_JniUtil
 * Method:    YUVRenderV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_utils_JniUtil_YUVRenderV
  (JNIEnv *, jclass);

/*
 * Class:     com_example_utils_JniUtil
 * Method:    YUVsetData
 * Signature: ([BIII)V
 */
JNIEXPORT void JNICALL Java_com_example_utils_JniUtil_YUVsetData
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

/*
 * Class:     com_example_utils_JniUtil
 * Method:    setH264Data
 * Signature: ([BIIII)V
 */
JNIEXPORT void JNICALL Java_com_example_utils_JniUtil_setH264Data
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_example_utils_JniUtil
 * Method:    hwPlayerInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_utils_JniUtil_hwPlayerInit
  (JNIEnv *, jclass);

/*
 * Class:     com_example_utils_JniUtil
 * Method:    hwPlayerDeinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_utils_JniUtil_hwPlayerDeinit
  (JNIEnv *, jclass);

/*
 * Class:     com_example_utils_JniUtil
 * Method:    hwPlayerPlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_utils_JniUtil_hwPlayerPlay
  (JNIEnv *, jclass);

/*
 * Class:     com_example_utils_JniUtil
 * Method:    hwPlayerStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_utils_JniUtil_hwPlayerStop
  (JNIEnv *, jclass);

/*
 * Class:     com_example_utils_JniUtil
 * Method:    sendNativeVoice
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_utils_JniUtil_sendNativeVoice
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
